export const DOSE_STATUS = {
  CURRENTLY_SHORTAGE: "CURRENTLY_SHORTAGE",
  SHORTAGE_RESOVLED: "SHORTAGE_RESOVLED",
  CURRENT_SHORTAGE_NOT_FOUND: "CURRENT_SHORTAGE_NOT_FOUND",
};

export const REPORTER_TYPE = {
  PATIENT: "PATIENT",
  PROVIDER: "PROVIDER",
};
